### ISSUE TITLE
Proposal: Register samples to Allen mouse atlas and use their structure hierarchy

### ISSUE THREAD

**Issue by stripathy** [oganm/brainCellTypeSpecificGenes#10]
e.g., Allen Institute says that medial habenula is part of the thalamus, not the midbrain: http://atlas.brain-map.org/atlas?atlas=2#atlas=2&plate=100883900&structure=186&x=7798.93359375&y=4024&zoom=-3&resolution=16.75&z=6

**Comment by oganm** [comment]
A hierarchy somewhat similar to Allen is implemented
